### ISSUE TITLE
TutorialView Storyboard

### ISSUE THREAD

**Issue by acegreen** [DavidBenko/TutorialView#4]
Hi,

I was wondering if we can create a ViewController with a UIView, assign the UIView class of TutorialView and draw labels and such on it, then do the draw error in code?

**Comment by DavidBenko** [comment]
Without testing I don't see why not, `TutorialView` is just a `UIView` subclass so you should be able to set the view in storyboard to the `TutorialView` class and then add the arrows with code, which should trigger the draw calls.
